"""QA for promoting Unicorns to a primary app screen."""

from __future__ import annotations

import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "app_v2_37.py"
UI = ROOT / "src/ui_v2_37/ui.py"


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def read_app_tree() -> ast.Module:
    return ast.parse(APP.read_text(encoding="utf-8"))


def find_screens(tree: ast.Module) -> dict[str, str]:
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "SCREENS":
                    require(isinstance(node.value, ast.Dict), "SCREENS must be a dict literal")
                    return {
                        key.value: value.value
                        for key, value in zip(node.value.keys, node.value.values)
                        if isinstance(key, ast.Constant) and isinstance(value, ast.Constant)
                    }
    raise AssertionError("SCREENS was not found")


def test_unicorns_is_primary_navigation_screen() -> None:
    screens = find_screens(read_app_tree())
    ordered_keys = list(screens)
    require("global_unicorns" in screens, "Unicorns screen missing from navigation")
    require(screens["global_unicorns"] == "🦄 Unicornios", "Unexpected Unicorns label")
    require(ordered_keys.index("global_unicorns") == 1, "Unicorns must be directly after Inicio")


def test_unicorns_has_dedicated_renderer_and_dispatch() -> None:
    source = APP.read_text(encoding="utf-8")
    ui_source = UI.read_text(encoding="utf-8")
    require("def render_global_unicorns(" in source, "Dedicated Unicorns renderer missing")
    require("def explain_unicorn_reason(" in source, "Detailed Unicorns explanation helper missing")
    require("def unicorn_criterion_badges(" in source, "Unicorn criteria badges helper missing")
    require('"global_unicorns": render_global_unicorns' in source, "Unicorns renderer missing from dispatch")
    require('row.get("unicorn_status") == "EVALUATED_UNICORN"' in source, "Unicorns screen must filter evaluated unicorns")
    require("No constituye asesoramiento financiero" in source, "Unicorns screen must preserve no-advice language")
    require('height=620' in source, "Unicorns table must be scrollable instead of visually capped")
    require('on_select="rerun"' in source, "Unicorns table must support row selection when Streamlit allows it")
    require("Detalle del unicornio" in source, "Unicorns screen must expose per-company detail")
    require("Por qué es unicornio" in source, "Unicorns screen must explain why each company is a unicorn")
    require("motivo técnico original" in source, "Unicorns screen must preserve original technical traceability")
    require("Tarjetas visuales" in source, "Unicorns screen must provide visual cards mode")
    require("Tabla completa" in source, "Unicorns screen must preserve complete table mode")
    require("Criterios cumplidos" in source, "Unicorns screen must show criterion badges/details")
    require("selected_unicorn_asset_id" in source, "Unicorns screen must keep selected card detail state")
    require("def unicorn_sort_key(" in source, "Unicorns screen must provide deterministic sort modes")
    require("Ordenar por" in source, "Unicorns screen must expose sorting")
    require("Top países" in source and "Top bolsas" in source, "Unicorns screen must show top country/exchange summaries")
    require("Exportar unicornios filtrados" in source, "Unicorns screen must export filtered unicorns")
    require("Comparar 2-3" in source and "Comparador de unicornios" in source, "Unicorns screen must compare selected unicorns")
    require("scout_finance_unicornios_filtrados_v2_44e.csv" in source, "Unicorns export filename must be versioned")
    require("def unicorn_watchlist_asset(" in source, "Unicorns screen must map rows into watchlist assets")
    require("Añadir a watchlist" in source, "Unicorn cards must support adding to watchlist")
    require("Añadir este unicornio a watchlist" in source, "Unicorn detail must support adding to watchlist")
    require("blocked_message(\"Añadir unicornios a watchlist\")" in source, "Unicorn watchlist writes must respect safe demo mode")
    require("atomic_write(watchlist_path, watchlist_data)" in source, "Unicorn watchlist writes must be persisted atomically")
    require("def unicorn_probability(" in source, "Unicorns screen must expose an explainable unicorn probability helper")
    require('col.expander("Ver detalle")' in source, "Unicorn card detail must open inline instead of relying on hidden scroll state")
    require("Posibilidad de unicornio" in source, "Unicorn cards/details must show unicorn probability")
    require("confianza de clasificación" in source, "Unicorn probability must be framed as classification confidence")
    require("no es probabilidad de rentabilidad" in source, "Unicorn probability must not imply expected return")
    require("No es precio objetivo" in source or "no es precio objetivo" in source, "Unicorn probability must not imply a price target")
    require("def professional_unicorn_report(" in source, "Unicorns screen must generate a professional report")
    require("Generar informe profesional" in source, "Unicorns screen must expose a clickable professional report action")
    require("Informe profesional de unicornio" in source, "Unicorn report must have a professional title")
    require("Resumen ejecutivo" in source and "Revision manual recomendada" in source, "Unicorn report must include professional sections")
    require("Tesis analitica personalizada" in source, "Unicorn report must include a company-specific analytical thesis")
    require("Matriz de senales" in source, "Unicorn report must include a signal matrix")
    require("Que podria hacer que deje de ser unicornio" in source, "Unicorn report must explain company-specific exit triggers")
    require("Fuente del flag unicornio" in source, "Unicorn report must expose the unicorn flag source")
    require("analytical_unicorn_takeaways" in source, "Unicorn report must use personalized analytical takeaways")
    require("Descargar informe Markdown" in source, "Unicorn report must be downloadable")
    require("Preparado para IA opcional futura" in source or "integración con IA queda preparada" in source, "Unicorn report must document optional future AI integration")
    require("sin llamadas externas" in source, "Unicorn report generation must remain offline in this phase")
    require("def unicorn_evidence_grade(" in source, "Unicorn cockpit must expose an evidence quality semaphore")
    require("Ranking interno de unicornios" in source, "Unicorn cockpit must expose internal unicorn ordering")
    require("Filtros rápidos" in source, "Unicorn cockpit must expose quick filters")
    require("def unicorn_radar_values(" in source, "Unicorn cockpit must expose radar evidence values")
    require("Notas personales" in source and "save_unicorn_notes" in source, "Unicorn cockpit must support local notes")
    require("Export pack investigación" in source, "Unicorn cockpit must export a research pack")
    require("Comparador profesional" in source, "Unicorn cockpit must include professional comparison")
    require("IA opcional para análisis extendido" in source, "Unicorn cockpit must prepare optional AI analysis without enabling network calls")
    require("Cockpit limpio" in source, "High-priority UX hardening must add a cleaner cockpit view")
    require("Búsqueda avanzada" in source, "High-priority search hardening must expose advanced search controls")
    require("Porcentaje mínimo" in source, "Advanced search must filter by minimum unicorn probability")
    require("Solo con notas personales" in source, "Advanced search must filter by local notes")
    require("def global_unicorn_executive_report(" in source, "Unicorns screen must generate a global executive report")
    require("Informe ejecutivo global de unicornios" in source, "Unicorns screen must expose the global executive report")
    require("Descargar informe ejecutivo global" in source, "Global executive report must be downloadable")
    require("UNICORN_REVIEW_STATUS_LABELS" in source, "Unicorn review history must define explicit local statuses")
    require("def load_unicorn_review_history(" in source, "Unicorn review history must load local review state")
    require("def save_unicorn_review_history(" in source, "Unicorn review history must persist local review state")
    require("Estado de revisión" in source, "Unicorn review history must be editable in the UI")
    require("PENDING" in source and "REVIEWED" in source and "FOLLOW" in source and "DISCARDED" in source, "Unicorn review statuses must cover pending/reviewed/follow/discarded")
    require("Última revisión" in source, "Unicorn review history must export last review timestamp")
    require("def unicorn_portfolio_report(" in source, "Unicorns screen must generate a portfolio/watchlist report")
    require("Portfolio/watchlist de unicornios" in source, "Unicorns screen must expose portfolio/watchlist grouping")
    require("Descargar portfolio Markdown" in source, "Unicorn portfolio must be downloadable as Markdown")
    require("Exportar portfolio CSV" in source, "Unicorn portfolio must be exportable as CSV")
    require("def unicorn_ai_prompt_template(" in source, "Unicorns screen must provide an optional AI prompt template")
    require("Prompt IA opcional" in source, "Unicorn AI template must be exposed in the UI")
    require("Descargar prompt IA" in source, "Unicorn AI prompt must be downloadable")
    require("No recomiendes comprar, vender ni mantener" in source, "Unicorn AI prompt must preserve no-advice guardrails")
    require("No des precio objetivo" in source, "Unicorn AI prompt must forbid price targets")
    require("def render_unicorn_presentation_mode(" in source, "Unicorns screen must provide a presentation/demo renderer")
    require("Presentación/demo" in source, "Unicorns screen must expose presentation/demo mode")
    require("Top 10 por evidencia local" in source, "Presentation mode must show top evidence-backed unicorns")
    require("Tres fichas destacadas" in source, "Presentation mode must show highlighted unicorn cards")
    require("Descargar resumen de presentación" in source, "Presentation mode must export a clean summary")
    require("def render_unicorn_full_catalog(" in source, "Unicorns screen must provide a full catalog/detail renderer")
    require("Fichas completas" in source, "Unicorns screen must expose full cards/detail mode")
    require("Todos los campos técnicos disponibles" in source, "Full detail must expose all available raw fields")
    require("Catálogo completo de unicornios filtrados" in source, "Full catalog must explain scrollable company selection")
    require("def render_unicorn_recalculation_panel(" in source, "Unicorns screen must expose a dedicated recalculation panel")
    require("Recalcular universo y unicornios" in source, "Unicorns screen must allow recalculating the local unicorn universe")
    require("Entraron" in source and "Salieron" in source, "Unicorn recalculation must show companies entering and leaving")
    require("No descarga datos nuevos ni consulta APIs" in source, "Recalculation must keep explicit no-network guardrails")
    require("def render_unicorn_visual_analytics(" in source, "Unicorns screen must expose visual analytics")
    require("Analítica visual" in source, "Unicorns visual analytics must be a first-class view")
    require("Timeline de señal" in source, "Visual analytics must include a signal timeline")
    require("Fórmula de señal" in source, "Visual analytics must include an explanatory formula panel")
    require("Feed de recálculo y revisión" in source, "Visual analytics must include a recalculation/review feed")
    require("Estado técnico" in source, "Visual analytics must expose technical state cards/table")
    require("Resumen visual" in source and "Informe completo personalizado" in source and "Datos técnicos" in source, "Visual analytics must organize each company into calm tabs")
    require("Descargar informe completo personalizado" in source, "Selected unicorn must expose the personalized full report directly")
    require("Vista más visual" in source, "Visual analytics must explicitly favor a more visual layout")
    require("tarjetas nítidas de selección" in source, "Visual analytics must use crisp visual selection cards")
    require("Ver ficha" in source, "Unicorn visual cards must open the selected company detail")
    require("unicorn_visual_card_select_" in source, "Unicorn visual card selector keys must be stable")
    require("dropdown borroso" in source, "Visual analytics must document replacing the blurry dropdown")
    require("unicorn_visual_company_selector" not in source, "Visual analytics must not use the native selectbox selector")
    require("← Anteriores" in source and "Siguientes →" in source, "Unicorn visual cards must provide previous/next navigation")
    require("unicorn_visual_cards_page" in source, "Unicorn card pagination state must be stable")
    require("page_size = 12" in source, "Unicorn visual card pagination must show 12 cards per page")
    require("st.rerun()" in source, "Unicorn card navigation must rerender after page changes")
    require("sf-live-ticker" in source, "Unicorn visual analytics must include a live activity ticker")
    require("sf-motion-card" in source, "Unicorn visual cards must use motion card styling")
    require("sf-confidence-fill" in source, "Unicorn visual cards must include animated confidence bars")
    require("@keyframes sfScan" in ui_source and "@keyframes sfPulseGlow" in ui_source, "Motion CSS must include scan and pulse animations")
    require("@keyframes sfSweep" in ui_source and "@keyframes sfProgressLoop" in ui_source, "Motion CSS must include obvious working-panel animations")
    require("sf-analysis-engine" in source, "Unicorn visual analytics must include an animated analysis engine panel")
    require("Motor local analizando unicornios" in source, "Animated analysis panel must be visibly labeled")
    require("sf-node-map" in source, "Animated analysis panel must include moving nodes")
    require("def render_unicorn_company_motion(" in source, "Selected company detail must include company-level motion")
    require("sf-gauge" in source and "sf-company-motion" in source, "Company detail must include an animated confidence gauge")
    require("sf-checklist" in source and "sf-verify-flow" in source, "Company detail must include animated checklist and verification flow")
    require("sf-signal-bars" in source, "Company detail must include staggered signal bars")
    require("@keyframes sfGaugePop" in ui_source and "@keyframes sfCheckIn" in ui_source, "Motion CSS must include company detail animations")
    require("prefers-reduced-motion" in ui_source, "Motion CSS must respect reduced motion preferences")
    require("EXPLOSIVE_UNICORN_REQUIRED_SIGNALS" in source, "Unicorns screen must define the required explosive-stock signals separately")
    require("def explosive_unicorn_status(" in source, "Unicorns screen must separate explosive unicorn evaluation from fundamental quality")
    require("def render_unicorn_semantic_split(" in source, "Unicorns screen must expose a conceptual split UI")
    require("Calidad fundamental" in source and "Unicornio explosivo" in source, "Unicorns screen must separate fundamental quality from explosive candidates")
    require("Breakout Stocks" in source and "Multibaggers" in source and "Short Squeeze" in source, "Explosive mode must name breakout/multibagger/squeeze explicitly")
    require("Penny Stocks" in source and "Micro-Caps" in source, "Explosive mode must name penny/micro-cap explicitly")
    require("capitalización, precio, volumen relativo, float, short interest" in source, "Explosive mode must require market data instead of reusing profitability alone")
    require("no como acciones explosivas" in source, "Legacy 161 cases must be reframed as fundamental quality, not explosive stocks")
    require("Faltan señales de mercado necesarias" in source, "Explosive mode must fail closed when market signals are missing")
    require("EXPLOSIVE_UNICORN_DATA_CONTRACT" in source, "Explosive candidates must define a formal data contract")
    require("def explosive_unicorn_contract_frame(" in source, "Explosive data contract must be renderable as a dataframe")
    require("def explosive_unicorn_missing_fields(" in source, "Explosive data contract must expose missing field diagnostics")
    require("def explosive_unicorn_contract_report(" in source, "Explosive data contract must export a Markdown report")
    require("market_cap_usd" in source and "relative_volume" in source and "short_float_pct" in source, "Explosive contract must include market cap, relative volume and short float")
    require("scout_finance_explosive_unicorn_data_contract_v2_45a.csv" in source, "Explosive contract CSV export must be versioned")
    require("scout_finance_explosive_unicorn_data_contract_v2_45a.md" in source, "Explosive contract Markdown export must be versioned")
    require("0 candidatos explosivos evaluables" in source, "Explosive contract report must preserve fail-closed current state")
    require("EXPLOSIVE_UNICORN_OVERLAY_PATH" in source, "Explosive candidate overlay path must be explicit")
    require("def explosive_unicorn_template_frame(" in source, "Explosive candidates must provide a local CSV template")
    require("def normalize_explosive_overlay(" in source, "Explosive overlay uploads must be validated")
    require("def load_explosive_overlay(" in source and "def save_explosive_overlay(" in source, "Explosive overlay must support local persistence")
    require("def apply_explosive_overlay(" in source, "Explosive overlay must merge market signals into local rows")
    require("def render_explosive_unicorn_overlay_import(" in source, "Explosive UI must expose template download and CSV upload")
    require("file_uploader(\"Subir CSV de señales explosivas\"" in source, "Explosive UI must allow uploading local market signals")
    require("scout_finance_explosive_unicorn_overlay_template_v2_45b.csv" in source, "Explosive template filename must be versioned")
    require("blocked_message(\"Guardar overlay de candidatos explosivos\")" in source, "Explosive overlay writes must respect safe demo mode")
    require("Overlay local guardado" in source, "Explosive overlay upload must confirm local persistence")
    require("def yfinance_symbol(" in source, "Explosive candidates must map compatible rows to provider symbols")
    require("def fetch_yfinance_explosive_overlay(" in source, "Explosive candidates must support automatic real market data refresh")
    require("import yfinance as yf" in source, "Automatic explosive refresh must use the existing yfinance dependency")
    require("Actualizar datos reales" in source, "Explosive UI must expose automatic real-data refresh")
    require("yfinance_real_market_snapshot_v2_45c" in source, "Automatic overlay rows must be source-tagged")
    require("Overlay automático guardado" in source, "Automatic provider refresh must persist a local overlay")
    require("Fallback manual v2.45B" in source, "Manual CSV must remain only as fallback after automatic provider support")
    require("sin broker, sin OpenAI y sin recomendacion" in source, "Automatic provider refresh must preserve guardrails")
    require("Motor explosivo" in source, "Explosive view must use a compact motor heading")
    require("Cache de mercado activa" in source, "Explosive view must summarize cache without showing the full table by default")
    require("Fallback manual y cache de mercado" in source, "Manual fallback/cache must be hidden in an expander")
    require("Contrato técnico y señales requeridas" in source, "Explosive technical contract must be hidden in an expander")
    require("def diversified_explosive_provider_sample(" in source, "Automatic provider refresh must use a diversified sample")
    require("sha1" in source, "Diversified provider sample must use stable hashing instead of alphabetical order")
    require("diversified_explosive_provider_sample(rows, limit)" in source, "yfinance refresh must call the diversified sampler")
    require(
        "sorted(rows, key=unicorn_internal_rank_key) if yfinance_symbol(row)" not in source,
        "yfinance refresh must not take the first alphabetic/internal-rank slice",
    )
    require("EXPLOSIVE_MARKET_DATA_PROVIDER_POLICY" in source, "Explosive market data providers must have an explicit policy")
    require("\"active_provider\": \"yfinance\"" in source, "yfinance must remain the active explosive market-data provider")
    require("\"blocked_execution_providers\": [\"metatrader\", \"broker_api\", \"trading_terminal\"]" in source, "Execution-oriented providers must remain blocked")
    require("def explosive_market_provider_status(" in source, "Explosive UI must expose provider status")
    require("Política de proveedores de mercado" in source, "Explosive UI must explain provider policy")
    require("sin broker · sin MetaTrader" in source, "Explosive UI must state that broker/MetaTrader are not active")
    require("def explosive_candidate_score(" in source, "Explosive candidates must have a dedicated score function")
    require("explosive_score_0_100" in source, "Explosive score must use an explicit 0-100 field")
    for tier in ["NO_DATA", "WATCH_ONLY", "EXPLOSIVE_CANDIDATE_LOW", "EXPLOSIVE_CANDIDATE_MEDIUM", "EXPLOSIVE_CANDIDATE_HIGH"]:
        require(tier in source, f"Explosive scoring tier {tier} must be present")
    require("No es una recomendación financiera ni predice rentabilidad" in source, "Explosive scoring must keep no-advice guardrail text")
    require("unicorn_internal_rank_key" in source, "Fundamental unicorn ranking must remain present")
    require("Score explosivo v1" in source, "Explosive UI must expose the dedicated score label")
    require("MetaTrader" in source and "broker_api" in source, "MetaTrader/broker must remain blocked after explosive scoring")
    require("\"active_provider\": \"yfinance\"" in source, "yfinance must remain the active provider after explosive scoring")
    require("def render_explosive_candidates_dashboard(" in source, "Explosive candidates must have a dedicated dashboard")
    require("Dashboard de candidatos explosivos" in source, "Explosive dashboard heading must be visible")
    require("Filtro de tier explosivo" in source, "Explosive dashboard must expose tier filters")
    require("Filtro de señal" in source, "Explosive dashboard must expose signal filters")
    for label in ["Micro-cap", "Penny stock", "Short squeeze", "Breakout", "Faltan datos críticos"]:
        require(label in source, f"Explosive dashboard filter {label} must be present")
    require("Por qué puntúa así" in source, "Explosive dashboard must explain score rationale")
    require("Qué revisar manualmente" in source, "Explosive dashboard must show manual review guidance")
    require("Resultado:" in source, "Explosive view must provide a compact result summary")


def main() -> None:
    test_unicorns_is_primary_navigation_screen()
    test_unicorns_has_dedicated_renderer_and_dispatch()
    print("v2.44B unicorns primary screen QA passed")


if __name__ == "__main__":
    main()
